import os
import django
import sys

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
django.setup()

from jobs.models import Neighborhood

neighborhoods_raw = """
AEOROPORT DE DOUALA
AKWA - 2 ÉGLISES
AKWA - ANCIEN 3ème
AKWA - ANCIEN PMUC
AKWA - BONADIBONG
AKWA - CARREFOUR DOUCHE
AKWA - CARREFOUR EQUIPEMENT
AKWA - CARREFOUR ORCA
AKWA - CARREFOUR SOUDANAISE
AKWA - CARREFOUR TIF
AKWA - CATHÉDRALE
AKWA - COLLEGE DE LA SALLE
AKWA - COLLEGE KING AKWA
AKWA - DE LASALLE
AKWA - HOPITAL LAQUINTINIE
AKWA - IMMEUBLE ACTIVA
AKWA - IMMEUBLE BATOULA
AKWA - IMMEUBLE DEKAGE
AKWA - MARCHE SANGDAGA
AKWA - MRS BEACH
AKWA - NGODI
AKWA - NOUVELLE ROUTE BONAKOUAMOUANG
AKWA - PALAIS DIKA AKWA
AKWA - RUE BEBEY EYIDI
AKWA - RUE DROUOT
AKWA - RUE FOCH
AKWA - SALLE DES FÊTES
AKWA - SONEL
AKWA NORD - CARRIERE
AKWA NORD - GULFIN
AKWA NORD - PADRE PIO
AKWA NORD - SANTA LUCIA
ANCIEN ABATTOIR
ANGE RAPHAËL - CAMPUS 1
ANGE RAPHAËL - CAMPUS 2
ANGE RAPHAËL - EGLISE DU 7E JOUR
ANGE RAPHAËL - MOBILE GUINNESS
ARI - BOCOM CASA
ARI - CARREFOUR CIMETIÈRE
ARI - NEPTUNE
BALI - EEC NJO NJO
BALI - KAYO ELIE
BALI - LOGEMENTS SONEL
BALI - MONTAGNE MANGA BELL
BALI - SGC
BALI - SISQO COIFFURE
BALI - SOMATEL
BANGUE - CARREFOUR BAOBAB
BANGUE - COLLEGE NAL
BANGUE - COLLEGE SOFRON
BANGUE - FIN GOUDRON
BANGUE - HOPITAL DE DISTRICT
BANGUE - MAISON BLANCHE
BANGUE - PETIT VOLTAIRE
BANGUE - THE WURI
BARCELONE
BASE NAVALE
BEEDI - HAUTE TENSION
BEEDI - MARCHE
BEEDI - PLATEAU
BEEDI - SAKER
BEPANDA - AMBIANCE
BEPANDA - AMERICAIN
BEPANDA - AN 2000
BEPANDA - CAMTEL
BEPANDA - CARREFOUR PASTEUR
BEPANDA - CASMANDO
BEPANDA - DOUBLE BALLES
BEPANDA - OMNISPORT
BEPANDA - ONE TO ONE
BEPANDA - PEUPLE
BEPANDA - SAFARI
BEPANDA - SANS CALEÇON
BEPANDA - TONNERRE
BEPANDA - YONG YONG
BESSENGUE - 3 MORTS
BESSENGUE - GARE CAMRAIL
BESSENGUE - VALLÉE
BILONGUE
BOIS DES SINGES - BENGHAZI
BOIS DES SINGES - BOCOM
BOIS DES SINGES - CARREFOUR KILO
BOIS DES SINGES - KOWEIT
BOIS DES SINGES - QUARTIER BAMENDA
BOJONGO - BRIGADE
BOJONGO - CARREFOUR HERVÉ
BOJONGO - CIMETIERE
BOJONGO - DERRIERE LE LYCEE
BOJONGO - PETROLEX
BOJONGO - STADE
BONABERI - 105 DERRIERE CHÂTEAU
BONABERI - 4 ETAGES
BONABERI - BABENGA SUPERMONT
BONABERI - BEKOKO
BONABERI - BESSEKE
BONABERI - BOCOM
BONABERI - BONANDALE PETIT PARIS
BONABERI - BONDJONGO JUSQU'À AGROCHEM
BONABERI - BWADIBO
BONABERI - CARREFOUR MUTZIG
BONABERI - CENTRE EQUESTRE
BONABERI - CHATEAU
BONABERI - CIBEC
BONABERI - COLLEGE DU LEVANT
BONABERI - DERRIERE ROYAL PALACE
BONABERI - DIKOLO FONO PLUS
BONABERI - DIKOLO GARAGE AMERICAIN
BONABERI - ECHANGEUR BEKOKO
BONABERI - ECHANGEUR FOKOU
BONABERI - ECOLE PNEU
BONABERI - FERMANCAM
BONABERI - FERME SUISSE
BONABERI - FIN GOUDRON
BONABERI - FORET BAR
BONABERI - GARE ROUTIERE
BONABERI - GRAND BAOBAB
BONABERI - GRAND HANGAR
BONABERI - HOPITAL AD LUCEM
BONABERI - ISEMBECK
BONABERI - LYCEE BILINGUE
BONABERI - MAMBANDA MARCHE
BONABERI - MPANJO CARREFOUR BLACK JO
BONABERI - MPANJO CARREFOUR NATURE
BONABERI - MPANJO COLLEGE LA ROSERAIE
BONABERI - MPANJO EGLISE 7EME JOUR
BONABERI - MUR NOIR
BONABERI - NANGA COMPAGNY
BONABERI - NDOBO CARREFOUR TASSI
BONABERI - NDOBO ECOLE LA REDOUTE
BONABERI - NDOBO GRAND TOH
BONABERI - NGWELE CENTRE ETAT CIVIL
BONABERI - NGWELE COLLEGE UNITE
BONABERI - NKOMBA
BONABERI - PETIT MARCHE
BONABERI - RAIL
BONABERI - RAIL SAWA LAMBO
BONABERI - ROI BELL
BONABERI - SANTA LUCIA
BONABERI - TOTAL NDOBO
BONABERI - USINE ALPICAM
BONABERI - WASHINGTON
BONABERI - ZONE INDUSTRIELLE
BONADIWOTO - GRAND MALL
BONAMATOUMBE
BONAMATOUMBE VILLAGE - CIMETIÈRE
BONAMOUSSADI - CARREFOUR ETOO
BONAMOUSSADI - CARREFOUR YORO JOSS
BONAMOUSSADI - COMMISSARIAT 12E
BONAMOUSSADI - DENVER
BONAMOUSSADI - DERRIERE CARREFOUR
BONAMOUSSADI - MARCHE
BONAMOUSSADI - MOSQUEE
BONAMOUSSADI - PETIT TERRAIN
BONAMOUSSADI - SANTA BARBARA
BONAMOUSSADI - SANTA LUCIA
BONAMOUSSADI - TERMINUS
BONANGANG
BONANJO - AIR FRANCE
BONANJO - GICAM
BONANJO - HOTEL MERIDIEN
BONANJO - LA FALAISE
BONANJO - MUSÉE MARITIME
BONANJO - POSTE CENTRALE
BONANJO - TOTAL NEUILLY 2
BONANJO - ZONE PORTUAIRE
BONANLOKA
BONANTONE
BONAPRISO
BONAPRISO - CARREFOUR ARMEE DE LAIR
BONAPRISO - CHEFFERIE UNHCR
BONAPRISO - CIMETIERE NJO NJO
BONAPRISO - HOTEL LA FALAISE
BONAPRISO - HYDROCARBURES
BONAPRISO - MARCHE DES FLEURS
BONAPRISO - PHARMACIE DEGAULLE
BONAPRISO - PHARMACIE KOLOKO
BONASSAMA - PALETUVIERS
BONASSAMA - ZONE INDUSTRIELLE
BONENDALE - ABATTOIRE
BONENDALE - ANTENNE ORANGE
BONENDALE - CARREFOUR ABATTOIR
BONENDALE - CARREFOUR SERGEO POLO
BONENDALE - CHEFFERIE
BONENDALE - ECOLE LETA
BONENDALE - ECOLE PUBLIQUE
BONENDALE - GENDARMERIE
BONENDALE - PETIT PARIS
BONENDALE - QUARTIER LATIN
BRAZZAVILLE
CAMP YABASSI
CHOCOCAM - UCB - HYSACAM
CITE DE LA PAIX
CITE DES PALMIERS - CARREFOUR EXPRESS
CITE DES PALMIERS - CARREFOUR LYCÉE
CITE DES PALMIERS - MARCHE
CITE DES PALMIERS - MOSQUÉE
CITE SIC - COLLEGE LAGAPE
CITE SIC - STADE MARION
DAKAR
DEIDO - AXE LOURD BONABASSEM
DEIDO - BONATEKI
DEIDO - BOULANGERIE COAF
DEIDO - ECOLE PUBLIQUE
DEIDO - PHARMACIE LA RIVE
DEIDO - PLAGE
DEIDO - ROND POINT
DEIDO - RUE DE LA JOIE
DEIDO - RUE DES STARS
DEIDO - SHANGAÏ
DIBAMBA
DIBAMBA - LEPROSERIE
ELF VILLAGE
GRAND MALL
GRAND MOULIN - CARREFOUR EFRAKATA
GRAND MOULIN - CERCLE MUNICIPAL
GRAND TOH NDOBO
JAPOMA - CARREFOUR GRAND BAR
JAPOMA - CARREFOUR LYCEE
JAPOMA - CARREFOUR MATANGO
JAPOMA - CHEFFERIE SUPERIEURE
JAPOMA - HOPITAL DE DISTRICT
JAPOMA - RAIL ROGER MILLA
JAPOMA - STADE
KASSALAFAM
KOTTO - BADEN BADEN
KOTTO - BOCOM
KOTTO - CARREFOUR DES IMMEUBLES
KOTTO - CARREFOUR LAC
KOTTO - CHEFFERIE
KOTTO - MRS
KOTTO - RESIDENCE
KOTTO - VILLAGE AU LAC
KOUMASSI
LENDI
LENDI - BOCOM
LENDI - CHEFFERIE
LENDI - ENTREE CAPITAINE
LENDI - MAISON BLANCHE
LENDI - PETIT PARIS
LENDI - STADE
LOGBABA - CENTRALE A GAZ
LOGBABA - FORESTIERE
LOGBABA - JARDIN
LOGBABA - MAIRIE
LOGBABA - ST THOMAS
LOGBABA - ZONE INDUSTRIELLE
LOGBESSOU - AD LUCEM
LOGBESSOU - CARREFOUR DALLAS
LOGBESSOU - CARREFOUR TANKOUA
LOGBESSOU - CRTV BAR
LOGBESSOU - DERRIERE COLLEGE SIMO QUARTIER DSCHANG
LOGBESSOU - JEAN PAUL 2
LOGBESSOU - TEMOINS
LOGPOM - 6È AVENUE
LOGPOM - BANGOSS
LOGPOM - CAMARA LAYE
LOGPOM - CARREFOUR ANDEM
LOGPOM - CARREFOUR BASSONG
LOGPOM - CARREFOUR DOCTA
LOGPOM - CARREFOUR TEMGOUA
LOGPOM - EGLISE EVANGELIQUE
LOGPOM - GABON BAR
LOGPOM - HOPITAL DES SOEURS
LOGPOM - MANDELA CITY
LOGPOM - MONTANA CITY
LOGPOM - NJOYA MAISON BLANCHE
LOGPOM - OBAMA CITY
LOGPOM - VALLEE DES ROIS
LOGPOM - ZONE CAMAIR
MADAGASCAR
MAKEA
MAKEPE - BIJOUX
MAKEPE - BM
MAKEPE - CARREFOUR ORLY
MAKEPE - COUR SUPRÊME
MAKEPE - MARIE LUMIERE
MAKEPE - PARCOURS VITA
MAKEPE - PETIT PAYS
MAKEPE - SAINT TROPEZ
MAKEPE - SAINTE MONIQUE
MAKEPE - VALLÉE
MAKEPE MISSOKE - ABIDJAN
MAKEPE MISSOKE - BOCOM
MAKEPE MISSOKE - MARCHE
MAKEPE MISSOKE - MOSQUÉE
MAKEPE MISSOKE - PONT CASSÉ
MALANGUE
MARCHE CONGO
MBANGA BAKOKO
MBANGA PONGO
MBANGA PONGO - PETIT ROBERT
MBANYA - SABLE
MBOPPI
MBWANG BAKOKO
NDOBO - TOTAL
NDOGAPSSI - BIENVENNUE
NDOGBATI
NDOGBONG - BIFAGA
NDOGBONG - CAMLAIT
NDOGBONG - COMMISSARIAT 10E
NDOGBONG - DAUPHINE
NDOGBONG - IMMEUBLE DES OFFICIERS
NDOGBONG - WINNER CHAPEL
NDOGBONG - ZACHMAN
NDOGPASSI - 1ER DANGER
NDOGPASSI - AFRIQUE DU SUD
NDOGPASSI - BOCOM
NDOGPASSI - BON PASTEUR
NDOGPASSI - BORNE 10
NDOGPASSI - CHAMP DES ANANAS
NDOGPASSI - CHAPELLE
NDOGPASSI - CHEFFERIE
NDOGPASSI - CHICAGO
NDOGPASSI - CITE DE LA PAIX
NDOGPASSI - COGEFAR 1ERE ENTREE
NDOGPASSI - COMMISSARIAT 14E
NDOGPASSI - ENTREE CARRIÈRE
NDOGPASSI - ENTREE ECOLE
NDOGPASSI - JARDIN
NDOGPASSI - MAITRE FOTSO
NDOGPASSI - MARCHE
NDOGPASSI - MARCHE GABONAIS
NDOGPASSI - MOSQUEE
NDOGPASSI - NYALLA CAMPO
NDOGPASSI - PETIT BONANJO
NDOGPASSI - QUÉBEC
NDOGPASSI - SONEL
NDOGPASSI - ST NICOLAS
NDOGPASSI - TRADEX
NDOGSIMBI
NDOKOTI
NEW BELL - AVIATION
NEW BELL - BABYLONE
NEW BELL - EGLISE BANDJOUN
NEW BELL - MBAM EWONDO
NEW BELL - NDJONG MEBI
NEW BELL - NKOLMITAG
NEW BELL - PRISON
NEW BELL - SEBENJONGO
NEW DEIDO - CAMP MAÏS
NGANGUE
NGODI BAKOKO - CARREFOUR ARI
NGODI BAKOKO - CARREFOUR GOUVERNEUR
NGODI BAKOKO - CHAMPS DE TIRS
NGODI BAKOKO - CIMETIERE
NGODI BAKOKO - ENIET
NGODI BAKOKO - LYCÉE
NGWELLE - INTERNAT MOTHER THEREZA
NKONGMONDO
NKOULOULOUN
NKOULOULOUN - DERNIER POTEAU
NYALLA - CAMBO
NYALLA - NKOLBONG
NYALLA - PARISO
NYALLA - QUARTIER HAOUSSA
NYLON
OYACK - ESPOIR
PK 10 - COLONEL NDI
PK 10 - GENIE MILITAIRE
PK 10 - MARCHE
PK 10 COLONEL NDI - SOEUR DOMINICAINE
PK 11 - MARIE CLAIRE
PK 11 - MBENGUE CITY
PK 11 - ST LOUIS
PK 12 - CAMP DES OFFICIERS
PK 12 - JARDIN PARADISIAQUE
PK 12 - KINDO
PK 12 - LYCEE VERS CAHETTE BAR
PK 12 - MANDJAP
PK 12 - MARCHE
PK 12 - NGO NJO FUTURA
PK 12 - NGOH NJO 2 SOUDEURS
PK 12 - QUARTIER BAMOUN
PK 12 À PK 14 DANS LE QUARTIER
PK 13 - BONAMOUTONGO
PK 13 - COMMISSARIAT
PK 14 - GROUPE SCOLAIRE DESCARTES
PK 14 - PAPAS ZONE G
PK 15 À PK 17
PK 17 - VERS CHEZ LE MASSEUR
PK 18 À PK 19
PK 21 - MANGOULE
PK 21 - MASSOUMBOU
PK 21 - PK 30
PK 8 - BELLAVIE LA ROCHE
PK 8 - EGLISE CATHOLIQUE
PK 8 - ENTREE LAÏC
PK 8 - ESG RENOVATION
PK 8 - TRESOR HÔTEL
PK 9 - COGEFAR BAO
ROND POINT CCC
SAINT MICHEL
SOBOUM
SODIKO VILLAGE - LYCEE
TEXACO AEROPORT
VILLAGE - ENTREE BILLES
VILLAGE - FRET AEOROPRT
VILLAGE - MBOKO
VILLAGE CHEFFERIE
VILLAGE SAINT NICOLAS
YANSOKI - UCAC
YASSA - TRADEX
YASSA NON LOIN DE LA ROUTE
YATIKA - DERRIERE ECOLE
YATIKA - UNIVERSITE CATHOLIQUE
YOUPWE - BOCOM
YOUPWE - CENTRE DES DECHETS
YOUPWE - MARCHE DU POISSON
YOUPWE - MARIANA 2000
YOUPWE BENGAZI
"""

neighborhoods_list = set([n.strip() for n in neighborhoods_raw.split('\n') if n.strip()])

# Delete all Douala neighborhoods
count, _ = Neighborhood.objects.filter(city__iexact='Douala').delete()
print(f"Deleted {count} existing neighborhoods for Douala.")

# Create new ones
created = 0
for name in sorted(list(neighborhoods_list)):
    Neighborhood.objects.create(city='Douala', name=name)
    created += 1

print(f"Inserted {created} neighborhoods for Douala.")
