import os
import django
import sys

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
django.setup()

from jobs.models import Neighborhood

neighborhoods_raw = """
ABOBO
ABOME
ACACIAS
ACROPOLE - MONTÉE ZOÉ
AFANOYA 1
AFANOYA 2
AFANOYA 3
AFANOYA 4
AHALA 1
AHALA 2
ANGUISSA
AVENUE GERMAINE
AWAE
AWAE CARREFOUR
AWAE ESCALIER
AWAE MVOG MANGA
AYENE
AZEGUE MESSA MEZALA
BASTOS
BITENG
BIYEM ASSI - SUPERETTE
BIYEM-ASSI
BRIQUETERIE
CABARET LA MEFOU - ENTREE MAETURE
CARREFOUR GOLF
CENTRE ADMINISTRATIF
CENTRE ADMINISTRATIF - EDUCATION
CENTRE ADMINISTRATIF - HOPITAL CENTRAL
CENTRE DES HANDICAPEES NKONDE
CITE U
CITE VERTE
CORON
DAKAR
DAKAR EN BAS
DERRIERE CENTRE DES HANDICAPEES
DERRIERE LE CAMP
DERRIERE PHARMACIE DU STADE OMNISPORT
DERRIERE ZIBI
DESCENTE ELEVEUR
DESCENTE HOPITAL GENERAL
DJONGOLO CENTRE ADMINISTRATIF
DRAGAGE
EBA BIYEM-ASSI
EBOT-MEFOU
ECOLE DE POLICE
EFOULAN
EKIE SUD ET NORD
EKOUDOU
EKOUMDOUM
EKOUNOU
EKOUNOU 2 CHEVEAUX
EKOUNOU IMPOT
ELEVEUR
ELEVEUR DERRIERE TRADEX
ELIG EDZOA
ELIG EFFA
ELIG-ESSONO
ELOUDEM
EMANA
EMOMBO
ENTREE AUTO ROUTE NKOLBISSON
ENTREE MINISTRE ELEVEUR
ESSOMBA
ESSOS
ETETACK
ETETACK ABOBO
ETOA MEKI 1
ETOKOS
ETOKOSS - MBALGONG
ETOUDI
ETOUG-EBE
ETOUG-EBE CENTRE DES HANDICAPEES
ETOUG-EBE I
ETOUG-EBE II
EWONKAN
FEBE VILLAGE
FOUGEROL CHATEAU
FOUGEROL PETIT MARCHE
GRAND ADMINISTRATIF
HIPPODROME - AVENUE DES BANQUES
HOTEL DE VILLE
IMMEUBLE T BELLA - MINCOM
INTENDANCE - IMMEUBLE JACO
JOUVENCE
KALAFATAS - SHO EQUIPEMENT - MTN
KOLOSSO APRES SIMBOCK
KONDENGUI
LEBOUDI 2 APRES NKOLBISSON
LEBOUDI APRES FEBE VILLAGE
MADAGASCAR
MANASSA
MANGUIER
MANGUIER CARREFOUR SORCIER
MARCHE CENTRAL
MARCHE MFOUNDI
MBALLA 1 NLONG MVOLYE
MBALLA 2
MBALLA 3
MBALLA V
MBANKOLO
MBANKOMO
MBOG-ABANG
MBOG-DOUM
MEKOUMBOU 1
MEKOUMBOU 2
MELEN
MELEN 1
MELEN 2
MELEN 3
MENDONG - GRANDE BARRIERE NKOLZIE
MENDONG CAMP SIC
MENDONG MARCHE
MESSA-CARRIERE
MESSAMENDONGO
MESSAMENDONGO DERRIERE
MESSASSI
MESSASSI NKOLNDOUM
MEYO
MFANDENA
MFOU
MFOUNDASSI
MIMBOMAN - DERNIER POTEAU
MIMBOMAN - DISPENSAIRE
MIMBOMAN - MAETUR
MIMBOMAN - OPEP
MIMBOMAN - PREMIERE CHAPELLE
MIMBOMAN CHARITE - FEICOM
MIMBOMAN DEUXIEME CHAPELLE
MIMBOMAN ECOLE
MIMBOMAN MVOG ENYEGUE
MIMBOMAN PLATEAU
MIMBOMAN TERMINUS
MINKAN
MINKOAMEYOS
MOBILE OMNISPORT
MOKOLO
MOKOLO MARCHE
MOKOLO QUARTIER
MONTEE ANNE ROUGE
MONTI
MVAN
MVOG-ADA
MVOG-ATANGANA MBALLA
MVOG-MAMBA
MVOG-MANZE
MVOG-MBI
MVOLYIE
NDAMVOUT
NGOA-EKELE 2
NGOULEMAKONG
NGOUSSO
NGOUSSO CHAPELLE
NGOUSSO CIMETIERE
NGOUSSO HOTEL LE PARADIS
NGOUSSO MOSQUEE
NGOUSSO RAIL
NGOUSSO-NTEM
NKOABANG
NKOABANG LADA MARRE D'EAU - ESSOK
NKOABANG-BANSANG
NKOAMETOU
NKOL ETON
NKOL-ASSI
NKOL-SO
NKOLAFAMBA
NKOLBIKOK
NKOLBIKOK II
NKOLBISSON
NKOLBISSON - LEBOUDI
NKOLBISSON AYENE
NKOLBISSON BEATTITUDE
NKOLBISSON DAGOBERT
NKOLFON
NKOLFOULOU
NKOLMESSENG - APRES LE CHEF
NKOLMESSENG - CHEZ LE BANQUIER
NKOLMESSENG 1
NKOLMESSENG 2
NKOLMESSENG 3
NKOLMESSENG-ELECAM
NKOLMESSENG-SAFARI
NKOLNDA
NKOLNDONGO
NKOMASSI
NKOMKANA I ET II
NKOMKANA III
NKOMO
NKOMO OKUI
NKOZOA
NLONGKAK
NLONGKAK EKOK ASSI
NNOMAYOS CONTROLE MIXTE
NSAM
NSAM - OBOBOGO
NSAM - SOFAVIN
NSIMALEN
NSIMEYONG 1
NSIMEYONG 2
NSIMEYONG 3
NSOA
NTOUESSONG
NTOUGOU I ET II
NYOM II
OBILI
OBOBOGO
ODZA
ODZA AUBERGE BLEU
ODZA BORNE 10
ODZA BORNE 12
ODZA CITE DE LA PAIX
ODZA ENTREE COETTE
ODZA KOETE
ODZA MONTEE ADVENTISTE
ODZA MVOG MANZE
ODZA PETIT MARCHE
ODZA PLAQUE LNB
ODZA TOTAL MAGZI
OKOLO
OLEMBE
OLEMBE BOULANGERIE DU PEUPLE
OLEMBE COEUR OUVERT
OLEMBE STADE
OLEZOA
OLIGA
OYOM ABANG 1
OYOM ABANG 2
OYOMAMBANG
POSTE CENTRALE
POSTE CENTRALE - AVENUE KENNEDY
QUARTIER FOUDA
QUARTIER GOLF
ROND POINT NSIMALEN
RUE CEPER
SIMBOCK
SOA
SOUS MANGUIER
TITI GARAGE
TKC
TONGOLO
TOTAL NGOUSSO
TOUTOULI
TROPICANA
TSINGA
TSINGA VILLAGE
VOGT
VOIRIE - OLEZOA
WARDA PALAIS DES SPORTS
"""

neighborhoods_list = set([n.strip() for n in neighborhoods_raw.split('\n') if n.strip()])

# Delete all Yaoundé neighborhoods
count, _ = Neighborhood.objects.filter(city__iexact='Yaoundé').delete()
print(f"Deleted {count} existing neighborhoods for Yaoundé.")

# Also delete if named 'Yaounde' (without accent)
count2, _ = Neighborhood.objects.filter(city__iexact='Yaounde').delete()
print(f"Deleted {count2} existing neighborhoods for Yaounde without accent.")

# Create new ones
created = 0
for name in sorted(list(neighborhoods_list)):
    Neighborhood.objects.create(city='Yaoundé', name=name)
    created += 1

print(f"Inserted {created} neighborhoods for Yaoundé.")
