# Generated by Django 6.0.5 on 2026-06-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'offre se termine pour l'auto-complétion", null=True),
        ),
    ]
