# Generated by Django 6.0.5 on 2026-06-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_joboffer_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='ad_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='ad_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
