# Generated by Django 6.0.5 on 2026-06-02 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_joboffer_ad_image_url_joboffer_ad_url'),
        ('users', '0003_candidateprofile_profile_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='users.employerprofile'),
        ),
    ]
