# Generated by Django 6.0.5 on 2026-06-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_joboffer_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
