# Generated by Django 6.0.5 on 2026-06-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_application_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='city',
            field=models.CharField(default='Douala', max_length=100),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='neighborhood',
            unique_together={('city', 'name')},
        ),
    ]
