# Generated by Django 6.0.5 on 2026-06-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employerprofile_city_employerprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_views',
            field=models.IntegerField(default=0),
        ),
    ]
