# Generated by Django 6.0.5 on 2026-06-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_candidateprofile_profile_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='generated_password',
            field=models.CharField(blank=True, help_text='Temporary password generated for admin view', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_type',
            field=models.CharField(choices=[('Salarié', 'Salarié'), ('Freelance', 'Freelance'), ('Apprenti', 'Apprenti'), ('Elève', 'Elève'), ('Etudiant', 'Etudiant')], default='Freelance', max_length=20),
        ),
    ]
