# Generated by Django 6.0.5 on 2026-06-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_candidateprofile_generated_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='StartJobs', max_length=100)),
                ('contact_email', models.EmailField(default='support@startjobs.cm', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_registrations', models.BooleanField(default=True)),
                ('require_email_verification', models.BooleanField(default=True)),
                ('seo_title', models.CharField(default='StartJobs - La plateforme des emplois pour jeunes', max_length=200)),
                ('seo_description', models.TextField(default='Trouvez rapidement des petits boulots et des offres de stage au Cameroun.')),
            ],
            options={
                'verbose_name': 'Paramètres du Site',
            },
        ),
    ]
