# Generated by Django 6.0.5 on 2026-06-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
