# Generated by Django 6.0.5 on 2026-06-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_candidateprofile_latitude_candidateprofile_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
