# Generated by Django 6.0.5 on 2026-06-17 18:05

from django.db import migrations


def auto_verify_users(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.update(is_email_verified=True)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_email_verified'),
    ]

    operations = [
        migrations.RunPython(auto_verify_users),
    ]
