# Generated by Django 6.0.5 on 2026-06-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='generated_password',
            field=models.CharField(blank=True, help_text='Temporary password generated for admin view', max_length=128, null=True),
        ),
    ]
