# Generated by Django 6.0.5 on 2026-06-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_employerprofile_generated_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='verification_requested',
            field=models.BooleanField(default=False),
        ),
    ]
