# Generated by Django 6.0.5 on 2026-06-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_employerprofile_verification_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notify_admins_on_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('super_admin', 'Super Admin'), ('moderator', 'Modérateur'), ('employer', 'Employeur'), ('candidate', 'Candidat')], default='candidate', max_length=20),
        ),
    ]
