# Generated by Django 6.0.5 on 2026-06-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_sitesettings_notify_admins_on_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_empty_offers_countdown',
            field=models.BooleanField(default=True),
        ),
    ]
