# Generated by Django 6.0.5 on 2026-06-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_sitesettings_show_empty_offers_countdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
