# Generated by Django 6.0.5 on 2026-06-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_candidateprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='highest_diploma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
