# Generated by Django 6.0.5 on 2026-06-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_candidateprofile_highest_diploma'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
