# Generated by Django 6.0.5 on 2026-06-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_candidateprofile_graduation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notify_admins_on_employer_registration',
            field=models.BooleanField(default=True),
        ),
    ]
