# Generated by Django 6.0.5 on 2026-06-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_sitesettings_notify_admins_on_employer_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='employer_type',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=20),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='kyc_document',
            field=models.FileField(blank=True, null=True, upload_to='employers/kyc/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='kyc_status',
            field=models.CharField(choices=[('unverified', 'Non vérifié'), ('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='suspend_employer_features',
            field=models.BooleanField(default=False),
        ),
    ]
