# Generated by Django 6.0.5 on 2026-06-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_employerprofile_employer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='kyc_document',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='kyc_attestation_fiscale',
            field=models.FileField(blank=True, null=True, upload_to='employers/kyc/entreprise/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='kyc_attestation_immatriculation',
            field=models.FileField(blank=True, null=True, upload_to='employers/kyc/entreprise/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='kyc_cni_recto',
            field=models.FileField(blank=True, null=True, upload_to='employers/kyc/cni/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='kyc_cni_verso',
            field=models.FileField(blank=True, null=True, upload_to='employers/kyc/cni/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='kyc_method',
            field=models.CharField(blank=True, help_text='cni, recepisse, passport, or none for entreprise', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='kyc_passport_recepisse',
            field=models.FileField(blank=True, null=True, upload_to='employers/kyc/passport/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='kyc_selfie',
            field=models.FileField(blank=True, null=True, upload_to='employers/kyc/selfies/'),
        ),
    ]
