# Generated by Django 6.0.5 on 2026-06-30 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_employerprofile_kyc_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='kyc_attestation_fiscale',
            field=models.FileField(blank=True, null=True, upload_to='employers/kyc/entreprise/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='kyc_attestation_immatriculation',
            field=models.FileField(blank=True, null=True, upload_to='employers/kyc/entreprise/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='kyc_cni_recto',
            field=models.FileField(blank=True, null=True, upload_to='employers/kyc/cni/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='kyc_cni_verso',
            field=models.FileField(blank=True, null=True, upload_to='employers/kyc/cni/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='kyc_passport_recepisse',
            field=models.FileField(blank=True, null=True, upload_to='employers/kyc/passport/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='kyc_selfie',
            field=models.FileField(blank=True, null=True, upload_to='employers/kyc/selfies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
